//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace HospitalMvc.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Datetimes
    {
        public int DatetimeID { get; set; }
        public int DoctorID { get; set; }
        public int PatientID { get; set; }
        public System.DateTime Time { get; set; }
    }
}
